full_image_path: !!python/str C:\Users\marke\Documents\DSC180A-Q1\raw_data\full_img\Engilchek_glacier_1999-08-26.tif
image_path: !!python/str C:\Users\marke\Documents\DSC180A-Q1\raw_data\ndsi_imgs\Engilchek_glacier_1999-08-26.tif